- name: Crear y configurar LXC en Proxmox
  hosts: proxmox
  become: yes

  tasks:
  - name: Crear contenedor LXC
    tags: create_lxc
    ansible.builtin.shell: 
      pct create {{ lxc_base_id }} {{ lxc_image }}
      --rootfs {{ rootfs_storage }}:{{ rootfs_size }}
      --swap {{ swap }}
      --cores {{ cores }}
      --cpulimit {{ cpu_limit }}
      --hostname lxc-{{ lxc_base_id }}
      --net0 name=eth0,bridge={{ bridge_name }},ip={{ bridge_ip }}.{{ lxc_base_id }}/24,gw={{ bridge_gw}}
      --password {{ lxc_password }}
      --features nesting=1,keyctl=1
    register: create_result
    failed_when: "'already exists' not in create_result.stderr and create_result.rc != 0"

  - name: Iniciar LXC
    tags: start_lxc
    ansible.builtin.shell: pct start {{ lxc_base_id }}